sudo: required
language: python
python:
    - "2.7"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
    - sudo add-apt-repository -y ppa:dns/gnu
    - sudo apt-get update -qq
    - export CXX="g++-4.8"
install:
    - sudo apt-get install automake
    - sudo apt-get install libboost-dev libboost-test-dev libboost-program-options-dev libevent-dev libtool flex bison pkg-config g++ libssl-dev
    # - sudo apt-get install build-essential libgtk2.0-dev libjpeg-dev libtiff4-dev libjasper-dev libopenexr-dev cmake python-dev python-numpy python-tk libtbb-dev libeigen3-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev libqt4-dev libqt4-opengl-dev sphinx-common texlive-latex-extra libv4l-dev libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev default-jdk libvtk5-qt4-dev
    #install grunt + grunt-cli
    - npm install grunt grunt-cli -g
    #install thrift
    - curl http://www.carfab.com/apachesoftware/thrift/0.9.3/thrift-0.9.3.tar.gz > thrift-0.9.3.tar.gz
    - tar -xf thrift-0.9.3.tar.gz
    - cd thrift-0.9.3
    - ./configure --without-ruby --without-go --without-php --without-erlang --without-perl
    - make -j4
    - sudo make install
    #build and install thrift.js for remote interface
    - cd lib/js
    - npm install
    - grunt --force
    - cp dist/thrift.js ../../../remote/public/javascripts/thrift.js
    - cd ../../..
    #install remote interface dependencies
    - cd remote
    - npm install
    - cd ..
    #install logging service dependencies
    - cd logging
    - npm install
    - cp ..
    #install opencv 2.4
    # - git clone https://github.com/Itseez/opencv.git
    # - cd opencv
    # - git checkout 2.4
    # - mkdir build
    # - cd build
    # - cmake ..
    # - make -j8
    # - sudo make -j8 install
    # - cd ../..
before_script:
    #generate thrift files and copy into place
    - sh thrift/gen.sh
script:
    #add test scripts here
    - node index.js &
    - npm test
